// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaGmCHyLDWExPHHnADocatZTqaXravB28',
    appId: '1:212874769680:web:a72d72e20eb2d0e9c76195',
    messagingSenderId: '212874769680',
    projectId: 'tech-25524',
    authDomain: 'tech-25524.firebaseapp.com',
    storageBucket: 'tech-25524.appspot.com',
    measurementId: 'G-B6TMT10JP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6xWqp8hSiA04aH45D0dSNqMyzPMTClA',
    appId: '1:212874769680:android:efdf3fa67079f776c76195',
    messagingSenderId: '212874769680',
    projectId: 'tech-25524',
    storageBucket: 'tech-25524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYIxPlO3GxvaiqwOyZWjm0zJ9jSpvRry4',
    appId: '1:212874769680:ios:5ba4c083e3e5e0f3c76195',
    messagingSenderId: '212874769680',
    projectId: 'tech-25524',
    storageBucket: 'tech-25524.appspot.com',
    iosBundleId: 'com.example.techsaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYIxPlO3GxvaiqwOyZWjm0zJ9jSpvRry4',
    appId: '1:212874769680:ios:5ba4c083e3e5e0f3c76195',
    messagingSenderId: '212874769680',
    projectId: 'tech-25524',
    storageBucket: 'tech-25524.appspot.com',
    iosBundleId: 'com.example.techsaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaGmCHyLDWExPHHnADocatZTqaXravB28',
    appId: '1:212874769680:web:6a5fd91de3caaf17c76195',
    messagingSenderId: '212874769680',
    projectId: 'tech-25524',
    authDomain: 'tech-25524.firebaseapp.com',
    storageBucket: 'tech-25524.appspot.com',
    measurementId: 'G-04L8WGVYQH',
  );
}
